### ISSUE TITLE
Change vnc desktop passwd

### ISSUE THREAD

**Issue by maintain001** [accetto/ubuntu-vnc-xfce-firefox#1]
hello , recently , I need to change vnc_passwd of my container , but i'dont know how to do this , I am trying to chang this passwd by using " -e VNC_PW=******* " but it not works .

**Comment by accetto** [comment]
Hello maintain001,

thank you for your feedback. 

I've just tested the following three cases and they've worked just fine - the VNC password has been changed to 'foo' in all three cases:

`docker run -d -P -e VNC_PW=foo --name=foo accetto/ubuntu-vnc-xfce-firefox-default`
`docker run -d -P -e VNC_PW=foo --name=foo accetto/ubuntu-vnc-xfce-firefox-plus`
`docker run -d -P -e VNC_PW=foo --name=foo accetto/ubuntu-vnc-xfce`

Could it be, that you've used spaces or special characters in your new password? In such case you have to use quotes - like this:

`docker run -d -P -e VNC_PW="foo 123" --name=foo accetto/ubuntu-vnc-xfce`

I've tested also this case and the new password has been successfuly set to 'foo 123' (with a space in the middle).

Test it once more please and let me know if it worked.

Regards,
accetto

**Comment by accetto** [comment]
Closing the issue after a week of no further comments.
