### ISSUE TITLE
deploy failure

### ISSUE THREAD

**Issue by ly3medic** [accetto/ubuntu-vnc-xfce-firefox#6]
i tried to deploy it to heroku but it didnt work due to this error :

(( ./vnc_startup.sh: line 47: /dockerstartup/.bashrc: No such file or directory ))

**Comment by accetto** [comment]
Thank you for the feedback. Indeed, there is the following part in the startup script `vnc_startup.sh`:

```bash
### '.bashrc' will also source '$STARTUPDIR/generate_container_user'
### (see 'stage-final' in Dockerfile)
source "${HOME}"/.bashrc
```

The file `.bashrc` is created by the Dockerfile, so it definitely should be there:

```Dockerfile
ENV \
    DISPLAY=:1 \
    HOME=${ARG_HOME:-/home/headless} \
    ...

### 'generate_container_user' has to be sourced to hold all env vars correctly
RUN echo 'source $STARTUPDIR/generate_container_user' >> ${HOME}/.bashrc
```

I would guess, that **heroku** has bound the `HOME` directory to an external volume and no `.bashrc` file is there. So you could try to create it yourself. Actually, I never used this **Generation 1** image with **heroku**, so I cannot say if it's really possible. I would need to test it first.

However, you should not have this problem with the newer **Generation 3** or **Generation 2** images. I would recommend, that you use the images [accetto/ubuntu-vnc-xfce-firefox-g3](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-firefox-g3) (Generation 3) or [accetto/xubuntu-vnc-novnc-firefox](https://hub.docker.com/r/accetto/xubuntu-vnc-novnc-firefox) (Generation 2) instead.

Please let me know, if the newer images work for you or if you still need to use the **Generation 1** image for some reason. I would test it with **heroku** then.
